spring:
  application:
    name: ryan-shiro-auth

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456

  redis:
    host: 127.0.0.1
    port: 6379

  thymeleaf:
    cache: false
    mode: LEGACYHTML5


mybatis:
  type-aliases-package: com.ryan.shiroauth.model
  mapper-locations: classpath:mapper/*.xml

